name: CI

on: 

  push:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
    
      - name: build
        run: |
          chmod +x gradlew
          ./gradlew build sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }} 
          
      - name: SonarCloud Analysis
        run: |
         chmod +x gradlew
         ./gradlew buil sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          scanMetadataReportFile: build/sonar/report-task.txt   
      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: CP raiz 
        run: |
          cp $GITHUB_WORKSPACE/build/libs/spring-petclinic-2.6.0.jar .
          chmod 777 spring-petclinic-2.6.0.jar
          ls -lt 
      
      - name: Docker Build
        run: | 
          docker build --tag clagosu/pet-clinic:latest .
          docker images

      - name: Docker Push
        run: |
          docker push clagosu/pet-clinic 

          deploy: 
          runs-on: self-hosted 
          needs: build
          steps: 
       
