name: CI

on: 

  push:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
    
      - name: build
        run: |
          chmod +x gradlew
          ./gradlew build sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }} 
          
      - name: SonarCloud Analysis
        run: |
         chmod +x gradlew
         ./gradlew buil sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          scanMetadataReportFile: build/sonar/report-task.txt   
          String  password = "123456789";

       
